### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by lozcalver** [AndrewHaine/silverstripe-form-capture#2]
This is kinda broken out of the box, it just shows the 3 summary fields and not actual submission data. It’s a tricky problem, as each form will have different fields so exporting to one CSV file would be very messy. As the data is split across tables, it’s also hard to avoid a large number of expensive database queries.

For one of our sites I hacked together a modified `GridFieldExportButton` which outputs one CSV file for each type of form: https://gist.github.com/kinglozzer/18c18344a94c5798d7127461e70e3cdd. (relies on `league/csv`, `league/flysystem` and `league/flysystem-ziparchive`).

While the above works, it may fall down at some point - most likely will hit memory and/or time limits. My suggestion would be to use the [queuedjobs module](https://github.com/symbiote/silverstripe-queuedjobs) and add a custom GridField button which will _schedule_ an export job. It’ll then run on CLI “later” (you can set it up to export smaller chunks at a time, in case one big job would time-out) and could export the data to a folder in assets. That could either be part of this module, and try to detect whether the module is installed before adding the export button, or an entirely separate module that depends on this one + queuedjobs.

**Comment by AndrewHaine** [comment]
Thank you for pointing this out. I've been doing a bit of work on this and I think this should be a separate module, queued jobs is quite a big module to install for somthing that might not get used much, will draft a module that adds a custom button/job. For now I've removed the standard gridfield buttons to avoid confusion

**Comment by lozcalver** [comment]
Just noticed this that may provide some inspiration: https://github.com/silverstripe/silverstripe-gridfieldqueuedexport.
